name: Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - master
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux-intel
            runs-on: ubuntu-latest
          - os: linux-arm
            runs-on: ubuntu-24.04-arm
          - os: windows-intel
            runs-on: windows-latest
          - os: windows-arm
            runs-on: windows-11-arm
          - os: macos-intel
            runs-on: macos-latest
          - os: macos-arm
            runs-on: macos-latest
          - os: pyodide
            runs-on: ubuntu-latest
            platform: pyodide

    steps:
    - uses: actions/checkout@v5

    - uses: pypa/cibuildwheel@v3.1.4
      env:
        CIBW_PLATFORM: ${{ matrix.platform || 'auto' }}

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        path: wheelhouse/*.whl
        name: dist-${{ matrix.os }}
